name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name : setup jakejarvis/s3-sync-action@master
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: 'us-east-1'
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
    - name: Run unit Test
        # run: node index.js
      run: python s3.py    
        
